name: Process docs component of Antora
on:
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.7
        with:
          files: |
            docs_from_alphadoc/**/*.adoc
            processAntoraDocsComponent.mjs
      - name: Changed files
        run: |
          echo ${{ steps.changed-files.outputs.all_changed_files }}
      - name: Process antora docs component
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          npm run processAntoraDocsComponent
      - name: Push Local Changes
        if: steps.changed-files.outputs.all_changed_files != ''
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: "Process docs component of Antora"
          branch: ${{ github.head_ref }}
